### ISSUE TITLE
MUSI "main" (2024121800) require booking > "main" (2024112800)

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/local_musi#17]
Bug: MUSI "main" (2024121800) require booking > "main" (2024112800)
![image](https://github.com/user-attachments/assets/ba924b26-91f2-41fd-bbcd-ffa55452c7a7)

**Comment by bernhard-wunderbyte** [comment]
- [x] Updated branch "**main**" of **mod_booking** to **Version 8.9.1 (2024121800)**
- [x] Updated branch "**main**" of **local_wunderbyte_table** to **Version 2.0.34 (2024121200)**
